### ISSUE TITLE
Docs about @nuxt/router

### ISSUE THREAD

**Issue by MichaelGitArt** [ergonode/vuems#15]
There is no information in the docs about @nuxt/router setup. Only from example application I understood I need add it and setup router.js this way

![image](https://user-images.githubusercontent.com/34610289/103685527-14f19f00-4f96-11eb-9493-9c0f482f4e7d.png)

P.S. Thanks for your package) There is no alternative solution  on the Internet for  vue or nuxt

**Comment by bleto** [comment]
Thank you for this issue :)

I am in the process of creating documentation.
This entry should solve all your questions: https://vuems.ergonode.com/router
(documentation is still under development).

If something is not clear yet, I will be very grateful for the information :)  

P.S.
In a few days, there will also be a repository with a demo.

**Comment by MichaelGitArt** [comment]
Thank you!
