### ISSUE TITLE
[Bug] Images not shown in the docs

### ISSUE THREAD

**Issue by skoenfaelt** [ergonode/vuems#20]
If you visit https://vuems.ergonode.com/usage/#modules-directory
you will see, that the image is not rendered (see attached files) 

![2021-05-25 13_13_55-Window](https://user-images.githubusercontent.com/53934248/119488709-22e46880-bd5b-11eb-912d-da6bb4d668ae.png)

I downloaded the docs and verified, that the images are present in development mode and after generating the prod build. So it seems to be a github pages bug?

**Comment by MichaelGitArt** [comment]
Please, fix it. I wanna use it module :)
