### ISSUE TITLE
Cannot read property 'registerModule' of undefined

### ISSUE THREAD

**Issue by Pirosauro** [ergonode/vuems#6]
### Expected behavior

store should be defined when registerModule is called or, at least, should check if it is defined.

### Current Behavior

The above error. 

### Steps to Reproduce

See [CodeSanbox](https://codesandbox.io/s/7vxy3)

### Context (Environment)

Latest nuxt-ts (2.14.4) 
It happens when ./store is empty. In my case I planned to use vuex but haven't started the development yet

**Comment by bleto** [comment]
Thanks for reporting :)
Tell me if you tried to set the `vuex = false` in your `nuxt.config.js` file? 
```
vuems: {
        ...
        vuex: false,
},
```

**Comment by bleto** [comment]
@Pirosauro 
If you have more questions or something is not clear, new documentation has been created.
https://vuems.ergonode.com/
